unit_aliases:
  "": unknown
  "M": m
  "METRE": m
  "METRES": m
  "FT": ft
  "US/F": us/ft
  "US/FT": us/ft
  "US/M": us/m
  "ΜS/M": us/m
  "ΜS/FT": us/ft
  "MV": mV
  "V": V
  "G/CM³": g/cm3
  "G/CM3": g/cm3
  "G/CC": g/cm3
  "KG/M3": kg/m3
  "%": percent
  "V/V": fraction
  "M3/M3": fraction
  "M^3/M^3": fraction
  "M³/M³": fraction
  "_": unknown
  "-": unknown
  "NONE": unknown
  "OHM-M": ohm.m
  "OHMM": ohm.m
  "API": API
  "GAPI": API
  "NULL": unknown
  "UNKNOWN": unknown
  "(M/S)*(G/CM³)": "(m/s)*(g/cm3)"
  "(M/S)*(G/CM3)": "(m/s)*(g/cm3)"
  "M/S*G/CM3": "(m/s)*(g/cm3)"
  "(M/S)*(KG/M3)": "(m/s)*(kg/m3)"
  "M/S*KG/M3": "(m/s)*(kg/m3)"
conversions:
  "ft->m": {scale: 0.3048, offset: 0}
  "m->ft": {scale: 3.280839895, offset: 0}
  "us/ft->us/m": {scale: 3.280839895, offset: 0}
  "kg/m3->g/cm3": {scale: 0.001, offset: 0}
  "(m/s)*(kg/m3)->(m/s)*(g/cm3)": {scale: 0.001, offset: 0}
  "percent->fraction": {scale: 0.01, offset: 0}
  "V->mV": {scale: 1000, offset: 0}
  "mm->cm": {scale: 0.1, offset: 0}
  "in->cm": {scale: 2.54, offset: 0}
  "ft/s->m/s": {scale: 0.3048, offset: 0}
  "s->ms": {scale: 1000, offset: 0}
